/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalCountRouteImport } from './routes/local-count'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedTodosIndexRouteImport } from './routes/_protected/todos/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTodosNewRouteImport } from './routes/_protected/todos/new'
import { Route as ProtectedTodosIdEditRouteImport } from './routes/_protected/todos/$id.edit'

const LocalCountRoute = LocalCountRouteImport.update({
  id: '/local-count',
  path: '/local-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedTodosIndexRoute = ProtectedTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTodosNewRoute = ProtectedTodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTodosIdEditRoute = ProtectedTodosIdEditRouteImport.update({
  id: '/todos/$id/edit',
  path: '/todos/$id/edit',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local-count': typeof LocalCountRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/todos/new': typeof ProtectedTodosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos/': typeof ProtectedTodosIndexRoute
  '/todos/$id/edit': typeof ProtectedTodosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local-count': typeof LocalCountRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/todos/new': typeof ProtectedTodosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos': typeof ProtectedTodosIndexRoute
  '/todos/$id/edit': typeof ProtectedTodosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/local-count': typeof LocalCountRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/todos/new': typeof ProtectedTodosNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/todos/': typeof ProtectedTodosIndexRoute
  '/_protected/todos/$id/edit': typeof ProtectedTodosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/local-count'
    | '/login'
    | '/sign-up'
    | '/todos/new'
    | '/api/auth/$'
    | '/todos/'
    | '/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/local-count'
    | '/login'
    | '/sign-up'
    | '/todos/new'
    | '/api/auth/$'
    | '/todos'
    | '/todos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/local-count'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_protected/todos/new'
    | '/api/auth/$'
    | '/_protected/todos/'
    | '/_protected/todos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LocalCountRoute: typeof LocalCountRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/local-count': {
      id: '/local-count'
      path: '/local-count'
      fullPath: '/local-count'
      preLoaderRoute: typeof LocalCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/todos/': {
      id: '/_protected/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof ProtectedTodosIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/todos/new': {
      id: '/_protected/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof ProtectedTodosNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/todos/$id/edit': {
      id: '/_protected/todos/$id/edit'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof ProtectedTodosIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedTodosNewRoute: typeof ProtectedTodosNewRoute
  ProtectedTodosIndexRoute: typeof ProtectedTodosIndexRoute
  ProtectedTodosIdEditRoute: typeof ProtectedTodosIdEditRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTodosNewRoute: ProtectedTodosNewRoute,
  ProtectedTodosIndexRoute: ProtectedTodosIndexRoute,
  ProtectedTodosIdEditRoute: ProtectedTodosIdEditRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  LocalCountRoute: LocalCountRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
