/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalCountRouteImport } from './routes/local-count'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosNewRouteImport } from './routes/todos/new'
import { Route as TodosIdEditRouteImport } from './routes/todos/$id.edit'

const LocalCountRoute = LocalCountRouteImport.update({
  id: '/local-count',
  path: '/local-count',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdEditRoute = TodosIdEditRouteImport.update({
  id: '/todos/$id/edit',
  path: '/todos/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local-count': typeof LocalCountRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local-count': typeof LocalCountRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/local-count': typeof LocalCountRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/local-count' | '/todos/new' | '/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/local-count' | '/todos/new' | '/todos/$id/edit'
  id: '__root__' | '/' | '/local-count' | '/todos/new' | '/todos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalCountRoute: typeof LocalCountRoute
  TodosNewRoute: typeof TodosNewRoute
  TodosIdEditRoute: typeof TodosIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/local-count': {
      id: '/local-count'
      path: '/local-count'
      fullPath: '/local-count'
      preLoaderRoute: typeof LocalCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/edit': {
      id: '/todos/$id/edit'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof TodosIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalCountRoute: LocalCountRoute,
  TodosNewRoute: TodosNewRoute,
  TodosIdEditRoute: TodosIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
